# Generated by Django 3.2.9 on 2021-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmasterapp', '0002_auto_20211207_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
