# Generated by Django 3.2.9 on 2021-12-08 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolioapp', '0002_auto_20211206_1924'),
        ('assetmasterapp', '0002_auto_20211207_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('average_purchase_price_mv', models.FloatField(default=0)),
                ('average_purchase_price_fifo', models.FloatField(default=0)),
                ('rate_of_return_mv', models.FloatField(default=0)),
                ('rate_of_return_fifo', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity', to='assetmasterapp.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity', to='portfolioapp.portfolio')),
            ],
        ),
    ]
