# Generated by Django 3.2.9 on 2021-12-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_alter_dashboard_owner'),
        ('pensionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pension',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='pension',
            name='dashboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='dashboardapp.dashboard'),
            preserve_default=False,
        ),
    ]
