# Generated by Django 3.2.9 on 2021-12-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionapp', '0002_auto_20211216_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='rate_of_return',
            field=models.FloatField(default=0),
        ),
    ]
