# Generated by Django 3.2.9 on 2021-12-16 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pensionapp', '0003_pension_rate_of_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAY', '납입'), ('RECEIVE', '수령')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_transaction', to=settings.AUTH_USER_MODEL)),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_transaction', to='pensionapp.pension')),
            ],
        ),
    ]
