# Generated by Django 3.2.9 on 2021-12-08 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import equitytransactionapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('DIVIDEND', '배당금'), ('SPLIT', '액면분할')], max_length=20)),
                ('quantity', equitytransactionapp.models.MinValueFloat()),
                ('purchase_price', models.FloatField(default=0)),
                ('price', equitytransactionapp.models.MinValueFloat(default=0)),
                ('transaction_fee', models.FloatField(default=0)),
                ('transaction_tax', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(default=' -', max_length=20, null=True)),
                ('split_flag', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('equity_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='equityapp.equity')),
            ],
        ),
    ]
