# Generated by Django 3.2.9 on 2021-12-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equitytransactionapp', '0002_rename_equity_owned_equitytransaction_equity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitytransaction',
            name='purchase_price',
        ),
    ]
